services:
    - type: web
      name: laravel-feedback
      runtime: php
      plan: free
      buildCommand: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          npm install && npm run build
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      startCommand: heroku-php-apache2 public/
      envVars:
          - key: APP_NAME
            value: 'Feedback Forms'
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            fromService:
                name: laravel-feedback
                type: web
                property: url
          - key: DB_CONNECTION
            value: pgsql
          - key: DB_HOST
            value: dpg-d1af0iumcj7s73ffcca0-a
          - key: DB_PORT
            value: 5432
          - key: DB_DATABASE
            value: feedback_gza9
          - key: DB_USERNAME
            value: feedback_gza9_user
          # For the database password, use a secret in Render
          - key: DB_PASSWORD
            value: cdfLe7UetsGv9bOHeRrvJ7VKdM78zTot
          - key: APP_KEY
            generateValue: true
          - key: LOG_CHANNEL
            value: stderr
          - key: VIEW_COMPILED_PATH
            value: /tmp/views
          - key: SESSION_DRIVER
            value: cookie
