services:
    - type: web
      name: laravel-feedback
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: true
          - key: DB_CONNECTION
            value: pgsql
          - key: DB_HOST
            value: dpg-d1af0iumcj7s73ffcca0-a
          - key: DB_PORT
            value: 5432
          - key: DB_DATABASE
            value: feedback_gza9
          - key: DB_USERNAME
            value: feedback_gza9_user
          - key: DB_PASSWORD
            value: cdfLe7UetsGv9bOHeRrvJ7VKdM78zTot
          - key: LOG_CHANNEL
            value: stderr
          - key: VIEW_COMPILED_PATH
            value: /tmp/views
          - key: SESSION_DRIVER
            value: cookie
